openapi: 3.1.0
info:
  version: 1.0.0
  title: AquaTrack app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of AquaTrack app
tags:
  - name: Auth
    description: Auth operations.
  - name: Users
    description: Users endpoints.
  - name: Water
    description: Water endpoints.
servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1
paths:
  /users:
    get:
      $ref: ../swagger/paths/users/get.yaml
    post:
      $ref: ../swagger/paths/users/post.yaml
  /users/{userId}:
    get:
      $ref: ../swagger/paths/users/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/users/patch.yaml
    delete:
      $ref: ../swagger/paths/users/delete.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
